Controllers/StudentController.cs
using CommonHelper.Constant;
using LAB1.Models;
using LAB1.Models.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LAB1.Controllers
{
	public class StudentController : Controller
	{
		private List<Student> _students;
		private readonly IUploadFileService _uploadFile;
		public StudentController(IUploadFileService uploadFile)
		{
			_uploadFile = uploadFile;
			_students = new List<Student>() {
				new Student()
				{
					Id = 101,
					Name = "Quốc Nam",
					Branch = Branch.IT,
					Gender = Gender.Male,
					IsRegular = true,
					Address = "A1-2018",
					Email = "nam@g.com",
				},
				new Student()
				{
					Id =102,
					Name = "Phạm Viêth",
					Branch = Branch.CE,
					Gender = Gender.Female,
					IsRegular =false,
					Address = "Hà Đông",
					Email = "pv@g.com",
				},
				new Student()
				{
					Id = 103,
					Name = "Văn Hoàn",
					Branch = Branch.EE,
					Gender = Gender.Male,
					IsRegular = false,
					Address = "Hà Nội",
					Email = "hoan@mail.com",
				},
				new Student()
				{
					Id =104,
					Name = "Văn Quang",
					Branch = Branch.BE,
					Gender = Gender.Female,
					IsRegular = true,
					Address = "Bắc Ninh",
					Email = "nvq@mail.com",

				}
			};
		}
		public IActionResult Index()
		{
			return View(_students);
		}
		public IActionResult Create()
		{
			ViewBag.AllGenders = Enum.GetValues(typeof(Gender)).Cast<Gender>().ToList();
			ViewBag.AllBranches = Enum.GetValues(typeof(Branch)).Cast<Branch>().ToList();
            return View();
		}
		[HttpPost]
		public async Task<IActionResult> Create(Student student,IFormFile AvatarFile)
		{
			if (ModelState.IsValid) {
                if (AvatarFile != null)
                {
                    if (AvatarFile != null && AvatarFile.Length > 0 && !ImageContentTypeConst.ContentTypes.Any(item => item == AvatarFile.ContentType))
                    {
                        TempData["ErrorMessage"] = "File phải là ảnh";
                        return View();
                    }
                    student.Avatar = await _uploadFile.UploadFile(AvatarFile);

                }
                student.Id = (_students.Last().Id) + 1;
                _students.Add(student);
                TempData["SuccessMessage"] = "Tạo mới thành công";
                return View("Index", _students);
            }
            ViewBag.AllGenders = Enum.GetValues(typeof(Gender)).Cast<Gender>().ToList();
            ViewBag.AllBranches = Enum.GetValues(typeof(Branch)).Cast<Branch>().ToList();
            return View();
        }
	}
}

ViewComponents/RenderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using LAB1.Models;

namespace LAB1.ViewComponents
{
    public class RenderViewComponent : ViewComponent
    {
        private List<MenuItem> MenuItems = new List<MenuItem>();
        public RenderViewComponent()
        {
            MenuItems = new List<MenuItem>() {
                new MenuItem() {Id=1, Name="Branches", Link="Branches/List" },
                new MenuItem() {Id=2, Name="Students", Link="Student/Index" },
                new MenuItem() {Id=3, Name="Subjects", Link="Subjects/List"},
                new MenuItem() {Id=4, Name="Courses", Link="Courses/List"}
            };
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("RenderLeftMenu", MenuItems);
        }
    }
}

Views/Shared/MyLayoutHelper.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Management Student</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <!-- Begin Top nav -->
    <partial name="TopNav" />
    <!-- End Top nav -->
    <div id="layoutSidenav">
        <!-- Begin Left menu -->
        <div id="layoutSidenav_nav">
            @await Component.InvokeAsync("Render")

        </div>
        <!-- End Left menu -->
        <!-- Begin Right content -->
        <div id="layoutSidenav_content">
            <!-- Begin Main -->
            <main>
                @RenderBody()
            </main>
            <!-- End Main -->
            <!-- Begin Footer -->
            <footer class="py-4 bg-light mt-auto">
                <partial name="Footer" />
            </footer>
            <!-- End Footer -->
        </div>
        <!-- End Right content -->
    </div>
    <script src="~/js/scripts.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LAB1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LAB1.styles.css" asp-append-version="true" />
</head>
<body>
    @if(TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success position-absolute text-center" role="alert">@TempData["SuccessMessage"]</div>

    }
    @if(TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger position-absolute text-center" role="alert">@TempData["ErrorMessage"]
        </div>

    }
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LAB1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LAB1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>