Models/Entity/Learner.cs
using Models.Entity;

namespace Models.Entity
{
    public class Learner
    {
        public Learner()
        {
            Enrollments = new HashSet<Enrollment>();
        }
        public int LearnerID { get; set; }
        public string? LastName { get; set; }
        public string? FirstMidName { get; set; }
        public DateTime EnrollmentDate { get; set; }
        public int MajorID { get; set; }
        public virtual Major? Major { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}

Controllers/LearnerController.cs
using LAB1.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Models.Entity;

namespace MyWebApp.Controllers
{
    public class LearnerController : Controller
    {
        private SchoolContext db;           
        public LearnerController(SchoolContext context)
        {
            db = context;
        }

        private int pageSize = 3;
        public IActionResult Index(int? mid,string? keyword)
        {
            var learners = (IQueryable<Learner>)db.Learners;
                    
            if (mid != null)
            {
                learners =learners
                    .Where(l => l.MajorID == mid)
                    .Include(m => m.Major);
            }
            if (keyword != null)
            {
                learners = learners.Where(item => item.FirstMidName != null && item.FirstMidName.ToLower()==keyword.Trim().ToLower());
                ViewBag.keyword = keyword;
            }
            //tính số trang
            int pageNum = (int)Math.Ceiling(learners.Count() / (float)pageSize);
            //trả số trang về view để hiển thị nav-trang
            ViewBag.pageNum = pageNum;
            //lấy dữ liệu trang đầu
            var result = learners.Take(pageSize).ToList();
            return View(result);
        }
        public IActionResult LearnerFilter(int? mid, string? keyword, int? pageIndex)
        {
            
            var learners = (IQueryable<Learner>)db.Learners;
            int page = (int)(pageIndex == null || pageIndex <= 0 ? 1 : pageIndex);
            if (mid != null)
            {
                learners = learners.Where(l => l.MajorID == mid); //lọc
                ViewBag.mid = mid; 
            }
            if (keyword != null)
            {
                learners = learners.Where(item=>item.FirstMidName !=null && item.FirstMidName.ToLower().Contains(keyword.ToLower()));
                ViewBag.keyword = keyword;
            }
            //tính số trang
            int pageNum = (int)Math.Ceiling(learners.Count() / (float)pageSize);
            ViewBag.pageNum = pageNum; 
           
            var result = learners.Skip(pageSize * (page - 1))
                            .Take(pageSize)
                            .Include(m => m.Major);
            return PartialView("LearnerTable", result);
        }
        public IActionResult LearnerByMajorID(int mid)
        {
            var learners = db.Learners
                .Where(l => l.MajorID == mid)
                .Include(m => m.Major).ToList();
            return PartialView("LearnerTable", learners);
        }

        public IActionResult Create()
        {
            
            var majors = new List<SelectListItem>();
            foreach (var item in db.Majors)
            {
                majors.Add(new SelectListItem { Text = item.MajorName, 
                    Value = item.MajorId.ToString() });
            }
            ViewBag.MajorID = majors;
            
            //ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("FirstMidName,LastName,MajorID,EnrollmentDate")] Learner learner)
        {
            if (ModelState.IsValid)
            {
                db.Learners.Add(learner);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            var majors = new List<SelectListItem>();
            foreach (var item in db.Majors)
            {
                majors.Add(new SelectListItem
                {
                    Text = item.MajorName,
                    Value = item.MajorId.ToString()
                });
            }
            ViewBag.Majors = majors;
            return View();
        }
        public IActionResult Edit(int id)
        {
            if (id == null || db.Learners == null)
            {
                return NotFound();
            }

            var learner = db.Learners.Find(id);
            if (learner == null)
            {
                return NotFound();
            }
            var majors = new List<SelectListItem>();
            foreach (var item in db.Majors)
            {
                majors.Add(new SelectListItem
                {
                    Text = item.MajorName,
                    Value = item.MajorId.ToString()
                });
            }
            ViewBag.MajorID = majors;
            return View(learner);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("LearnerID, FirstMidName,LastName,MajorID,EnrollmentDate")] Learner learner)
        {
            if (id != learner.LearnerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(learner);
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LearnerExists(learner.LearnerID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.MajorId = new SelectList(db.Majors, "MajorID", "MajorName", learner.MajorID);
            return View(learner);
        }
        private bool LearnerExists(int id)
        {
            return (db.Learners?.Any(e => e.LearnerID == id)).GetValueOrDefault();
        }

        public IActionResult Delete(int id)
        {
            if (  db.Learners == null || id==null)
            {
                return NotFound();
            }

            var learner = db.Learners.Include(l => l.Major)
                .Include(e => e.Enrollments)
                .FirstOrDefault(m => m.LearnerID == id);
            if (learner == null)
            {
                return NotFound();
            }
            if(learner.Enrollments.Count()>0)
            {
                return Content("This learner has some enrollments, can't delete!");
            }    
            return View(learner);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (db.Learners == null)
            {
                return Problem("Entity set 'Learners' is null.");
            }
            var learner = db.Learners.Find(id);
            if (learner != null)
            {
                db.Learners.Remove(learner);
            }

            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

ViewComponents/MajorViewComponent.cs
using LAB1.Data;
using Microsoft.AspNetCore.Mvc;
using Models.Entity;


namespace MyWebApp.ViewComponents
{
    public class MajorViewComponent:ViewComponent

    {
        SchoolContext db;
        List<Major> majors;
        public MajorViewComponent(SchoolContext _context) {
            db = _context;
            majors = db.Majors.ToList();
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("RenderMajor", majors);
        }
    }
}

Views/Learner/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/MyLayoutHelper.cshtml";
}
@model Models.Entity.Learner

<div class="ms-2 mx-2">
    <h1>Create</h1>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-controller="Learner" asp-action="Create" method="post" class="mt-3">
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="FirstMidName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="FirstMidName" class="form-control" placeholder="First Mid Name">
            </div>
            <span asp-validation-for="FirstMidName" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="LastName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="LastName" class="form-control" placeholder="Last Name">
            </div>
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="MajorID" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <select asp-for="MajorID" class="custom-select mr-sm-2"
                        asp-items="@ViewBag.MajorID"></select>
            </div>
            <span asp-validation-for="MajorID" class="text-danger"></span>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="EnrollmentDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="EnrollmentDate" class="form-control">
            </div>
            <span asp-validation-for="EnrollmentDate" class="text-danger"></span>
        </div>

        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </div>
    </form>
</div>

Views/Learner/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/MyLayoutHelper.cshtml";

}
@model Models.Entity.Learner

<div class="ms-2 mx-2">
    <h1>Delete</h1>
    <h3>Are you sure you want to delete this?</h3>
    <h4>Learner</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstMidName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Major)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Major.MajorName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EnrollmentDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EnrollmentDate)
        </dd>       
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="@Model.LearnerID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Learner/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/MyLayoutHelper.cshtml";

}



@model Models.Entity.Learner
<div class="ms-2 mx-2">
    <h1>Edit</h1>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-controller="Learner" asp-action="Edit" asp-route-id="@Model.LearnerID" method="post" class="mt-3">
        <input type="hidden" asp-for="LearnerID" />
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="FirstMidName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="FirstMidName" class="form-control" placeholder="First Mid Name">
            </div>
            <span asp-validation-for="FirstMidName" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="LastName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="LastName" class="form-control" placeholder="Last Name">
            </div>
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="MajorID" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <select asp-for="MajorID" class="custom-select mr-sm-2"
                        asp-items="@ViewBag.MajorID"></select>
            </div>
            <span asp-validation-for="MajorID" class="text-danger"></span>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="EnrollmentDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="EnrollmentDate" class="form-control">
            </div>
            <span asp-validation-for="EnrollmentDate" class="text-danger"></span>
        </div>

        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Edit</button>
            </div>
        </div>
    </form>
</div>

Views/Learner/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/MyLayoutHelper.cshtml";
}

@model IEnumerable<Models.Entity.Learner>
<div class="ms-2 mx-2">
    <h1>Learner List</h1>
    @await Component.InvokeAsync("Major")
    <form id="search-form" class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input id="keyword" class="form-control" name="keyword"
                   type="text" placeholder="Search learner" />
            <button id="btnSearch" class="btn btn-primary" type="submit">
                <i class="fas fa-search"></i>
            </button>
        </div>
    </form>
    <div id="content">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Mã</th>
                    <th>Tên</th>
                    <th>Họ</th>
                    <th>Ngành</th>
                    <th>Ngày Nhập Học</th>
                    <th>Chức năng</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var s in Model)
                {
                    <tr>
                        <td>@s.LearnerID</td>
                        <td>@s.FirstMidName</td>
                        <td>@s.LastName</td>
                        <td>@s.Major.MajorName</td>
                        <td>@s.EnrollmentDate</td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@s.LearnerID">Edit</a>|
                            <a asp-action="Delete" asp-route-id="@s.LearnerID">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
        <ul class="pagination">
            @for (int i = 1; i <= ViewBag.pageNum; i++)
            {
                <li class="page-item" page="@i"
                @(ViewBag.mid != null ? "mid='ViewBag.mid'" : "")
                @(ViewBag.keyword != null ? "keyword='@ViewBag.keyword'":"")>
                    <a class="page-link">@i</a>
                </li>
            }

        </ul>
    </div>
    <a asp-action="Create" class="btn btn-primary">Create New Student</a>
</div>
@section Scripts {
    <script>
        $('body').on('click', 'li.page-item', function (e) {
            //do your javascript here..
            var page = $(this).attr("page");
            var mid = $(this).attr("mid");
            var keyword = $(this).attr("keyword");
            var data = { mid: mid, keyword: keyword, pageIndex: page };
            $.ajax({
                url: "Learner/LearnerFilter",
                data: data,
                success: function (response) {
                    $("div#content").html(response);
                }
            });
        });

        $(".nav li").click(function (e) {
            var id = $(this).attr("id");
            var data = { mid: id };
            $.ajax({
                url: "Learner/LearnerFilter",
                data: data,
                success: function (response) {
                    $("div#content").html(response);
                }
            });
        });
        $("#search-form").on("submit",function (e) {
            var keyword = $("#keyword").val();
            var data = { keyword: keyword };
            $.ajax({
                url: "Learner/LearnerFilter",
                data: data,
                success: function (response) {
                    $("div#content").html(response);
                }
            });
        });
       
    </script>
}

Views/Learner/LearnerTable.cshtml
@model IEnumerable<Models.Entity.Learner>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Mã</th>
            <th>Tên</th>
            <th>Họ</th>
            <th>Ngành</th>
            <th>Ngày Nhập Học</th>
            <th>Chức năng</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
            <tr>
                <td>@s.LearnerID</td>
                <td>@s.FirstMidName</td>
                <td>@s.LastName</td>
                <td>@s.Major.MajorName</td>
                <td>@s.EnrollmentDate</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@s.LearnerID">Edit</a>|
                    <a asp-action="Delete" asp-route-id="@s.LearnerID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<ul class="pagination">
    @for (int i = 1; i <= ViewBag.pageNum; i++)
    {
        <li class="page-item" page="@i"
        @(ViewBag.mid != null ? "mid=" + ViewBag.mid : "")
         @(ViewBag.keyword != null ? "keyword=" + ViewBag.keyword : "") >
            <a class="page-link">@i</a>
        </li>
    }
</ul>